# This file was generated by GoReleaser. DO NOT EDIT.
cask "monogit" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "fb32c666f86c2356dc83ad6cc1a1b59d737c2ddb4990f928e4319f7611d6ce00"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a50a7f6fc855aadb1641a3f9b4bb994ea80bc3ce63090ee1be8a9becddf80fd1"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6424ad5dd187b15477244d9cf5e18ba1561498fa413671a156b38921909dd7f8"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8f0c2dc0d234e27c625b1b609aab97c088170842f4fe6a02797511efadf369fc"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Linux_arm64.tar.gz"
    end
  end

  name "monogit"
  desc "Terminal dashboard for managing multiple Git repositories"
  homepage "https://github.com/JoaoOliveira889/monogit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monogit"

  # No zap stanza required

end
