# This file was generated by GoReleaser. DO NOT EDIT.
cask "monogit" do
  version "0.3.4"

  on_macos do
    on_arm do
      sha256 "81da509c2d10e2f84d6dcb6bb40f1c15c40017131a15a58d555793e48ac97fa4"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ea063edc0a4e0eb992ad6a20f82afb3b654cd5ce68fb047d9201d87c33e5fe8"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6aa18bdf4e37f9bf7a7915015c7123156d4351d1d30aaf06b745e083bc718372"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "68bdb07f2c3b9fff69b1bb33f51d7b2130184736396e71d1a7c6336e48d9c6b5"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Linux_x86_64.tar.gz"
    end
  end

  name "monogit"
  desc "Terminal dashboard for managing multiple Git repositories"
  homepage "https://github.com/JoaoOliveira889/monogit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monogit"

  # No zap stanza required
end
