# This file was generated by GoReleaser. DO NOT EDIT.
cask "monogit" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "20ee7dff2b806522765e4e8ae7c2fd6585c081f1273bf557fc93e1fd2deb0f03"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f021975375aa7d7ab3b5a1c5f9919b053c6f75b74930e60d5dbd8adb52568c8b"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d7da867acecc666f9e95e04b99dadb2802ed4890a153e4f0d3d977c1632d7ce"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "06c7e21c953b60e78ea3ba63e6dec46b140d43c4c9f4e10ecee494a5faf10816"
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v#{version}/monogit_Linux_x86_64.tar.gz"
    end
  end

  name "monogit"
  desc "Terminal dashboard for managing multiple Git repositories"
  homepage "https://github.com/JoaoOliveira889/monogit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monogit"

  # No zap stanza required
end
