# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monogit < Formula
  desc "Terminal dashboard for managing multiple Git repositories"
  homepage "https://github.com/JoaoOliveira889/monogit"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.11/monogit_Darwin_x86_64.tar.gz"
      sha256 "eb1998b937a1bf18e84ce5a97d5bbf4f16473c83471ab57a85ee42ca8415c874"

      define_method(:install) do
        bin.install "monogit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.11/monogit_Darwin_arm64.tar.gz"
      sha256 "44fb296d24e9bc0284a12eacd5f2e9a6c4ea7ca0a1c880c86fa90558a4d8f0c3"

      define_method(:install) do
        bin.install "monogit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.11/monogit_Linux_x86_64.tar.gz"
      sha256 "17706d075f8cb6ce3bfecfa4468281e97d69903ac20bdd4a07e16c5579c2f642"
      define_method(:install) do
        bin.install "monogit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.11/monogit_Linux_arm64.tar.gz"
      sha256 "9b5b947d40b4ce9dbca50b459c39227b62f25bc48e7da396fc2e05870919ceb1"
      define_method(:install) do
        bin.install "monogit"
      end
    end
  end

  test do
    system "#{bin}/monogit --version"
  end
end
