# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monogit < Formula
  desc "Terminal dashboard for managing multiple Git repositories"
  homepage "https://github.com/JoaoOliveira889/monogit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.2.0/monogit_Darwin_x86_64.tar.gz"
      sha256 "4c590efd340f0bf742ad2e87ed02340b79b46dccc4fdcf0e2e844ef3d71f5015"

      define_method(:install) do
        bin.install "monogit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.2.0/monogit_Darwin_arm64.tar.gz"
      sha256 "0efac6d4e4b546b20a6891cc61add2ba1f4cc438b784ea6e93f686bb38b52a0c"

      define_method(:install) do
        bin.install "monogit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.2.0/monogit_Linux_x86_64.tar.gz"
      sha256 "25fd4697b7cba108c4b683dd1f9ba7711af4abf7b6bd98e77f8dc4e4d4e2343d"
      define_method(:install) do
        bin.install "monogit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.2.0/monogit_Linux_arm64.tar.gz"
      sha256 "967f847bd23f4ae3d081e5ce36f5b2621f3db785ca4f52adbf5d68086dd94873"
      define_method(:install) do
        bin.install "monogit"
      end
    end
  end

  test do
    system "#{bin}/monogit --version"
  end
end
