# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monogit < Formula
  desc "Terminal dashboard for managing multiple Git repositories"
  homepage "https://github.com/JoaoOliveira889/monogit"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.3/monogit_Darwin_x86_64.tar.gz"
      sha256 "cb03cc36af9117346e2494445d395a8d970ca1da26821a8ee66834789107739b"

      define_method(:install) do
        bin.install "monogit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.3/monogit_Darwin_arm64.tar.gz"
      sha256 "3647068d20d943a1e98e63db66a108de61909f1a6fc281f4c3dd33b14aecf662"

      define_method(:install) do
        bin.install "monogit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.3/monogit_Linux_x86_64.tar.gz"
      sha256 "b5e376baaf1222d6712b0f10a73b45a3038c7d76133d55f947165873d4ebd32b"
      define_method(:install) do
        bin.install "monogit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monogit/releases/download/v0.0.3/monogit_Linux_arm64.tar.gz"
      sha256 "296da1f256aa3082f80db3d4de303aed167d619038e7b19de740a686e126f59a"
      define_method(:install) do
        bin.install "monogit"
      end
    end
  end

  test do
    system "#{bin}/monogit --version"
  end
end
