# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monobox < Formula
  desc "Terminal UI for Docker and Podman containers"
  homepage "https://github.com/JoaoOliveira889/monobox"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoaoOliveira889/monobox/releases/download/v0.0.1/monobox_0.0.1_darwin_amd64.tar.gz"
      sha256 "126bb3cb4a6c8849b7c4d5c496002cc355e3b0b131b71d03b5a75556e97c16f1"

      define_method(:install) do
        bin.install "monobox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoaoOliveira889/monobox/releases/download/v0.0.1/monobox_0.0.1_darwin_arm64.tar.gz"
      sha256 "ab4470f7bca5816b62639f95574579806da6350299fa82dc14b3f2e726a12f05"

      define_method(:install) do
        bin.install "monobox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monobox/releases/download/v0.0.1/monobox_0.0.1_linux_amd64.tar.gz"
      sha256 "a9c5b97179a4f63b95638c61245cf0fedf417f794132b086ccccafddb60c22ce"
      define_method(:install) do
        bin.install "monobox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monobox/releases/download/v0.0.1/monobox_0.0.1_linux_arm64.tar.gz"
      sha256 "252c7d559ba52397496f9363587f44fad9094d40d070024e0d92835f03a6293a"
      define_method(:install) do
        bin.install "monobox"
      end
    end
  end

  test do
    system "#{bin}/monobox", "--version"
  end
end
