# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monostack < Formula
  desc "Multi-service AWS dashboard for your terminal"
  homepage "https://github.com/JoaoOliveira889/monostack"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoaoOliveira889/monostack/releases/download/v0.1.1/monostack_Darwin_x86_64.tar.gz"
      sha256 "981d59f32d36cf86e0f710cc19e133371e1cce7c90875b1ef9cb888e1ad1e7f4"

      define_method(:install) do
        bin.install "monostack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoaoOliveira889/monostack/releases/download/v0.1.1/monostack_Darwin_arm64.tar.gz"
      sha256 "546411d38e3faea107393e9c6c01b109a39a9371dfb1420b51423aee83108e66"

      define_method(:install) do
        bin.install "monostack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monostack/releases/download/v0.1.1/monostack_Linux_x86_64.tar.gz"
      sha256 "66a681758d6f952dfb9bc6aa8a932e5a2f4b56e3e6c4e5bae54384e471acd74d"
      define_method(:install) do
        bin.install "monostack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoaoOliveira889/monostack/releases/download/v0.1.1/monostack_Linux_arm64.tar.gz"
      sha256 "954cfd7a1eae2af5061f68afe58e08035621deed3e0b1b42ea56c30a1166203d"
      define_method(:install) do
        bin.install "monostack"
      end
    end
  end

  test do
    system "#{bin}/monostack --version"
  end
end
